In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
from scipy.stats import linregress
from scipy.stats import sem
import numpy as np

In [2]:
df1=pd.read_csv('Food_data.csv')
df2 = pd.read_csv('consumer_price_index_energy.csv')[['REF_DATE', 'VALUE']].rename(columns={'VALUE': 'Energy'})
df3 = pd.read_csv('consumer_price_index_mort_int.csv')[['REF_DATE', 'VALUE']].rename(columns={'VALUE': 'Mortgage_and_Interest'})
df4 = pd.read_csv('consumer_price_index_food.csv')[['REF_DATE', 'VALUE']].rename(columns={'VALUE': 'Food'})
df5 = pd.read_csv('consumer_price_index_gasoline.csv')[['REF_DATE', 'VALUE']].rename(columns={'VALUE': 'Gasoline'})
df6 = pd.read_csv('consumer_price_index_shelter.csv')[['REF_DATE', 'VALUE']].rename(columns={'VALUE': 'Shelter'})

In [3]:
# Merge the DataFrames based on the 'REF_DATE' column
df_food_price = pd.merge(df1, df2, on='REF_DATE', how='left')
df_food_price = pd.merge(df_food_price, df3, on='REF_DATE', how='left')
df_food_price = pd.merge(df_food_price, df4, on='REF_DATE', how='left')
df_food_price = pd.merge(df_food_price, df5, on='REF_DATE', how='left')
df_food_price = pd.merge(df_food_price, df6, on='REF_DATE', how='left')
# Print the merged DataFrame
df_food_price

,REF_DATE,GEO,DGUID,Commodity groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS,Energy,Mortgage_and_Interest,Food,Gasoline,Shelter
0,2007-01,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.30,77.4,NaN,NaN,NaN,1,125.2,-0.3,110.9,126.4,114.8
1,2007-02,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.30,78.3,NaN,NaN,NaN,1,127.1,-0.3,112.6,131.3,114.9
2,2007-03,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.30,80.6,NaN,NaN,NaN,1,135.9,-0.4,112.2,147.6,115.4
3,2007-04,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.30,79.0,NaN,NaN,NaN,1,139.1,-0.3,112.2,151.4,116.2
4,2007-05,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.30,78.6,NaN,NaN,NaN,1,142.0,-0.3,112.5,159.7,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4891,2023-08,Western Canada,NaN,Unprocessed milk [A25],"Index, 2007=100",181,units,0,v66449969,9.14,133.3,NaN,NaN,NaN,1,218.4,-1.0,185.3,247.8,174.0
4892,2023-09,Western Canada,NaN,Unprocessed milk [A25],"Index, 2007=100",181,units,0,v66449969,9.14,135.8,NaN,NaN,NaN,1,216.2,-0.8,185.2,244.7,174.8
4893,2023-10,Western Canada,NaN,Unprocessed milk [A25],"Index, 2007=100",181,units,0,v66449969,9.14,139.3,NaN,NaN,NaN,1,206.2,-0.7,185.0,229.1,176.3
4894,2023-11,Western Canada,NaN,Unprocessed milk [A25],"Index, 2007=100",181,units,0,v66449969,9.14,142.2,NaN,NaN,NaN,1,202.3,-0.6,186.2,221.1,177.1
4895,2023-12,Western Canada,NaN,Unprocessed milk [A25],"Index, 2007=100",181,units,0,v66449969,9.14,140.8,NaN,NaN,NaN,1,197.0,-0.4,186.8,211.3,177.8

In [4]:
df_food_price.head(500)

,REF_DATE,GEO,DGUID,Commodity groups,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS,Energy,Mortgage_and_Interest,Food,Gasoline,Shelter
0,2007-01,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.3,77.4,NaN,NaN,NaN,1,125.2,-0.3,110.9,126.4,114.8
1,2007-02,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.3,78.3,NaN,NaN,NaN,1,127.1,-0.3,112.6,131.3,114.9
2,2007-03,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.3,80.6,NaN,NaN,NaN,1,135.9,-0.4,112.2,147.6,115.4
3,2007-04,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.3,79.0,NaN,NaN,NaN,1,139.1,-0.3,112.2,151.4,116.2
4,2007-05,Canada,2016A000011124,Grains [A11],"Index, 2007=100",181,units,0,v66449854,1.3,78.6,NaN,NaN,NaN,1,142.0,-0.3,112.5,159.7,116.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,2014-04,Canada,2016A000011124,Specialty crops [A13],"Index, 2007=100",181,units,0,v66449856,1.5,119.0,NaN,NaN,NaN,1,171.2,-1.2,134.6,193.2,132.4
496,2014-05,Canada,2016A000011124,Specialty crops [A13],"Index, 2007=100",181,units,0,v66449856,1.5,118.8,NaN,NaN,NaN,1,172.7,-1.2,135.7,194.8,132.6
497,2014-06,Canada,2016A000011124,Specialty crops [A13],"Index, 2007=100",181,units,0,v66449856,1.5,119.7,NaN,NaN,NaN,1,173.0,-1.3,136.4,198.7,132.2
498,2014-07,Canada,2016A000011124,Specialty crops [A13],"Index, 2007=100",181,units,0,v66449856,1.5,120.5,NaN,NaN,NaN,1,171.9,-1.3,136.5,195.0,132.6
499,2014-08,Canada,2016A000011124,Specialty crops [A13],"Index, 2007=100",181,units,0,v66449856,1.5,112.9,NaN,NaN,NaN,1,168.3,-1.3,135.9,188.8,132.4

In [5]:
# Drop columns with mostly NaN values or not relevant for analysis
columns_to_drop = ['DGUID', 'SCALAR_FACTOR', 'UOM', 'UOM_ID', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'STATUS', 'SYMBOL', 'TERMINATED', 'DECIMALS']
df_food_price = df_food_price.drop(columns=columns_to_drop, axis=1)
df_food_price.head()

,REF_DATE,GEO,Commodity groups,VALUE,Energy,Mortgage_and_Interest,Food,Gasoline,Shelter
0,2007-01,Canada,Grains [A11],77.4,125.2,-0.3,110.9,126.4,114.8
1,2007-02,Canada,Grains [A11],78.3,127.1,-0.3,112.6,131.3,114.9
2,2007-03,Canada,Grains [A11],80.6,135.9,-0.4,112.2,147.6,115.4
3,2007-04,Canada,Grains [A11],79.0,139.1,-0.3,112.2,151.4,116.2
4,2007-05,Canada,Grains [A11],78.6,142.0,-0.3,112.5,159.7,116.0

In [6]:
# Convert all column names to lowercase
df_food_price.columns = df_food_price.columns.str.lower().str.replace(' ', '_')
# Print the DataFrame to verify the changes
df_food_price.head()

,ref_date,geo,commodity_groups,value,energy,mortgage_and_interest,food,gasoline,shelter
0,2007-01,Canada,Grains [A11],77.4,125.2,-0.3,110.9,126.4,114.8
1,2007-02,Canada,Grains [A11],78.3,127.1,-0.3,112.6,131.3,114.9
2,2007-03,Canada,Grains [A11],80.6,135.9,-0.4,112.2,147.6,115.4
3,2007-04,Canada,Grains [A11],79.0,139.1,-0.3,112.2,151.4,116.2
4,2007-05,Canada,Grains [A11],78.6,142.0,-0.3,112.5,159.7,116.0

In [7]:
# Convert 'REF_DATE' column to datetime format
df_food_price['ref_date'] = pd.to_datetime(df_food_price['ref_date'])

In [8]:
# Extract year and month as separate numerical features
df_food_price['year'] = df_food_price['ref_date'].dt.year
df_food_price['month'] = df_food_price['ref_date'].dt.month

In [9]:
# Drop the original 'REF_DATE' column
df_food_price.drop('ref_date', axis=1, inplace=True)

In [10]:
df_food_price.rename(columns={'commodity groups':'commodity_groups'},inplace=True)

In [11]:
# Using isin to seperate
options=['Unprocessed milk [A25]','Specialty crops [A13]']
new_df=df_food_price[df_food_price['commodity_groups'].isin(options)]
new_df.head()

,geo,commodity_groups,value,energy,mortgage_and_interest,food,gasoline,shelter,year,month
408,Canada,Specialty crops [A13],86.5,125.2,-0.3,110.9,126.4,114.8,2007,1
409,Canada,Specialty crops [A13],90.0,127.1,-0.3,112.6,131.3,114.9,2007,2
410,Canada,Specialty crops [A13],92.9,135.9,-0.4,112.2,147.6,115.4,2007,3
411,Canada,Specialty crops [A13],97.1,139.1,-0.3,112.2,151.4,116.2,2007,4
412,Canada,Specialty crops [A13],97.6,142.0,-0.3,112.5,159.7,116.0,2007,5

In [12]:
new_df.to_csv("clean_food_data.csv", index=False)